# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76ce9c2225859247a8531a2efdf179804fb81cd263a3d61f037ab025bad4c101c659ca262ef263b22b0c9816eea15870fe472f6a0b3e5c5018023218d4107859

test:
  secret_key_base: c37245a35c4f0d92eab45002d3471ee1c5b7fc701fc9b6d932d8686e216f5821c7f3ed2ef537fcbb82022e317cdcbfb4050c5ab89137528913531bd72fcba9bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
